FIRST_SECTOR:=arch/$(ARCH)/boot/boot.bin 
OBJS:=arch/$(ARCH)/kernel_entry.o arch/$(ARCH)/drivers/ATA_read_sector.o
LINKER_SCRIPT:=./arch/$(ARCH)/linker.ld
INCLUDES:=-I./arch/$(ARCH) -I./arch/$(ARCH)/boot/ -I./arch/$(ARCH)/utils